name: CI Workflow
on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout code
        run: |

         ls 
      # Add your build and test steps here
